name: Feed-Heal
main: Feed\Heal\FHMain
api: 4.0.0
version: 1.0.0
commands:
  heal:
    description: "Heil dich mit der macht des Experten"
    aliases: [Heal]
  feed:
    description: "Füttere dich mit der macht des MCPEExperten"
    aliases: [Feed]
permissions:
  server.heal:
    description: "Heal perm"
    default: false
  server.feed:
    description: "Feed perm"
    default: false